-- AlterTable
ALTER TABLE `medicine` ADD COLUMN `batchNumber` VARCHAR(191) NULL,
    ADD COLUMN `expiryDate` DATETIME(3) NULL,
    ADD COLUMN `status` ENUM('IN_STOCK', 'LOW_STOCK', 'CRITICAL', 'OUT_OF_STOCK') NOT NULL DEFAULT 'IN_STOCK',
    ADD COLUMN `stock` INTEGER NOT NULL DEFAULT 0;
